In [12]:
import numpy as np


In [13]:
# create from lists
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [15]:
arr2D=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,arr2D.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [16]:
arr2=np.zeros((2,3))
print(arr2,arr2.shape)

[[0. 0. 0.]
 [0. 0. 0.]] (2, 3)


In [3]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]] (2, 3)


In [4]:
reshape=arr.reshape((3,2))
print(reshape,reshape.shape)

[[1 2]
 [3 4]
 [5 6]] (3, 2)


In [5]:
flat=arr.flatten()
print(flat,flat.shape)

[1 2 3 4 5 6] (6,)


In [15]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6]]) 
idx=np.array([[0,0],[1,1]])
print(arr1[idx])

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
